id regularly for the entire premium payment term and the policy is in force. Guaranteed Maturity Benefit payable at maturity is inclusive of Basic Sum Assured plus Accrued Guaranteed Yearly<sup>1</sup> Additions plus Guaranteed Loyalty<sup>2</sup> Addition. <sup>1</sup>Guaranteed Yearly Additions is a percentage of Cumulative Annualized Premium<sup>#</sup> paid every year based on the opted premium payment term. It will accrue throughout the premium payment term and will be paid out at Maturity or on Death. <sup>#</sup>Annualized Premium is the premium payable in a policy year, excluding the taxes, rider premium underwriting extra premiums and loadings for modal premium, if any. <sup>2</sup>Guaranteed Loyalty Addition is a percentage of Basic Sum Assured and be paid out at Maturity. The rate of such addition will be based on the opted premium payment term.
</p><p><sup>^</sup>The above illustration is for an 18-year-old healthy male, non-smoker who is willing to invest Rs. 7,000 per month and will pay for 10 years for this policy; where the policy term is 15 years, the basic sum assured is Rs. 8,53,034 and guaranteed maturity benefit is Rs.14,61,141. The premium is assuming the policy is bought Online. The above premium figures are exclusive of Goods and Services Tax and Cess. Goods and Services Tax and Cess thereon shall be charged as per the prevalent tax laws over and above the said premiums.
</p>
<p>Ref No - KLI/22-23/E-BB/1318 </p>

<p>Guaranteed benefits due under this plan are available provided premiums are paid regularly for the entire premium payment term and the policy is in force. Guaranteed Maturity Benefit payable at maturity is inclusive of Basic Sum Assured plus Accrued Guaranteed Yearly<sup>1</sup> Additions plus Guaranteed Loyalty<sup>2</sup> Addition. <sup>1</sup>Guaranteed Yearly Additions is a percentage of Cumulative Annualized Premium<sup>#</sup> paid every year based on the opted premium payment term. It will accrue throughout the premium payment term and will be paid out at Maturity or on Death. <sup>#</sup>Annualized Premium is the premium payable in a policy year, excluding the taxes, rider premium underwriting extra premiums and loadings for modal premium, if any. <sup>2</sup>Guaranteed Loyalty Addition is a percentage of Basic Sum Assured and be paid out at Maturity. The rate of such addition will be based on the opted premium payment term.
</p><p><sup>^</sup>The above illustration is for an 18-year-old healthy male, non-smoker who is willing to invest Rs. 10,000 per month and will pay for 10 years for this policy; where the policy term is 15 years, the basic sum assured is Rs. 12,18,620 and guaranteed maturity benefit is Rs. 20,87,344. The premium is assuming the policy is bought Online. The above premium figures are exclusive of Goods and Services Tax and Cess. Goods and Services Tax and Cess thereon shall be charged as per the prevalent tax laws over and above the said premiums.
</p>

<p>Ref no. KLI/22-23/E-BB/1365</p>

<p>Guaranteed benefits due under this plan are available provided premiums are paid regularly for the entire premium payment term and the policy is in force. Guaranteed Maturity Benefit payable at maturity is inclusive of Basic Sum Assured plus Accrued Guaranteed Yearly<sup>1</sup> Additions plus Guaranteed Loyalty<sup>2</sup> Addition. <sup>1</sup>Guaranteed Yearly Additions is a percentage of Cumulative Annualized Premium<sup>#</sup> paid every year based on the opted premium payment term. It will accrue throughout the premium payment term and will be paid out at Maturity or on Death. <sup>#</sup>Annualized Premium is the premium payable in a policy year, excluding the taxes, rider premium underwriting extra premiums and loadings for modal premium, if any. <sup>2</sup>Guaranteed Loyalty Addition is a percentage of Basic Sum Assured and be paid out at Maturity. The rate of such addition will be based on the opted premium payment term.
 </p>  <p><sup>^</sup>The above illustration is for an 18-year-old healthy male, non-smoker who is willing to invest Rs. 10,000 per month and will pay for 10 years for this policy; where the policy term is 15 years, the basic sum assured is Rs. 12,18,620 and guaranteed maturity benefit is Rs. 20,87,344. The premium is assuming the policy is bought Online. The above premium figures are exclusive of Goods and Services Tax and Cess. Goods and Services Tax and Cess thereon shall be charged as per the prevalent tax laws over and above the said premiums.
</p>

<p>Ref No. KLI/22-23/E-BB/1456</p>

<p><sup>^</sup>The above illustration is for an 18-year-old healthy male, non-smoker who is willing to invest Rs. 1,760 per month and will pay for 10 years for this policy; where the policy term is 20 years, the basic sum assured is Rs. 3,18,040. The premium is assuming the policy is bought Online. The above premium figures are exclusive of Goods and Services Tax and Cess. Goods and Services Tax and Cess thereon shall be charged as per the prevalent tax laws over and above the said premiums.</p>

<p>Kotak Mahindra Life Insurance Company Ltd. Regn. No.: 107, CIN: U66030MH2000PLC128503, Regd. Office: 8th Floor, Plot # C-12, G-Block, BKC, Bandra (E), Mumbai-400 051. Website: <a href="<?php echo base_url()?>">www.kotaklife.com</a>|WhatsApp: 9321003007 | Toll Free No.: 1800 209 8800. </p>
<p>Trade Logo displayed above belongs to Kotak Mahindra Bank Limited and is used by Kotak Mahindra Life Insurance Company Ltd. under license.</p>
      </div>
    </div>
  </article>
  <!-- midWrapper End -->
</section>
<!-- Section End -->